project("./Cujana.xcodeproj")
scheme("CujanaScreenshots")
test_target_name("CujanaUITests")
ios_version(ENV["SCREENSHOT_IOS_VERSION"]) unless ENV["SCREENSHOT_IOS_VERSION"].to_s.empty?
languages(["de-DE", "en-US"])
clear_previous_screenshots(true)
skip_open_summary(true)
output_simulator_logs(true)
override_status_bar(true)
concurrent_simulators(true)
launch_arguments(["-mt_screenshot_seed default"])
devices([
  "iPhone 15 Pro Max",
  "iPad Pro 13-inch (M4)"
])
headless(false)
